### ISSUE TITLE
Return capital letters to media_title

### ISSUE THREAD

**Issue by GunterAv** [thlucas1/homeassistantcomponent_soundtouchplus#22]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thlucas1/homeassistantcomponent_soundtouchplus/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

...

### Describe the solution you'd like

Hello,

I have a request.
Is it possible to format the media_title always the same?

I have several Soundtouch devices unfortunately the media_title is returned differently per
device.
If devices are grouped, the formatting of the media_title may also change.

Sample:
media_title: BAYERN 3
or 
media_title: Bayern 3

![Gross](https://github.com/user-attachments/assets/6604cef0-bb53-4177-936b-ff5b83ff35b8)

![klein](https://github.com/user-attachments/assets/445e71b4-0e47-4505-b144-aadea7ec445e)

Is it possible that all letters are returned as capital letters to media_title?

Thank you and best regards
Gunter

### Describe alternatives you've considered

...

### Additional context

...

**Comment by thlucas1** [comment]
It would be the responsibility of the HA media player lovelace UI card to handle formatting issues like these, as the HA media player entity (e.g. soundtouchplus) simply passes what the Bose webservices API provides from the content issuer (e.g. Spotify, Pandora, SiriusXM, etc).

With that said, let me check a few things and see what it would take.

**Comment by GunterAv** [comment]
Hello,

Thank you for your time.

I read the attribute media_title and switch a button on or off, but if the text changes, the button is not switched on.

Best regards
Gunter

**Comment by thlucas1** [comment]
Hi Gunter - I don't think I can do this, as it exposes security vulnerabilities in the integration.  By allowing a user to build a format string, it would allow malicious actors (not you, of course) to gain access to variables within HA that they should not be able to access outside of the code.

I'm sorry, but I must refer to my original statement of:
It would be the responsibility of the HA media player lovelace UI card to handle formatting issues like these.

**Comment by GunterAv** [comment]
Hello,

Thank you for your feedback.

Best regards
Gunter
